name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni klonlash
        uses: actions/checkout@v4

      - name: PHP va Composer o‘rnatish
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer, phpunit
          coverage: none

      - name: Composer orqali bog‘liqliklarni o‘rnatish
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Muhit sozlamalarini yaratish
        run: cp .env.example .env

      - name: Laravel kalitini yaratish
        run: php artisan key:generate

      - name: Ma’lumotlar bazasini migratsiya qilish
        run: |
          php artisan migrate --force

      - name: Unit testlarni ishlatish
        run: php artisan test
